Azizsigar-w2
HackYourAssignment/Assignments-cohort48 pull request #11
Opened 2024-04-29 20:22 UTC by azizsigar

2024-04-29 20:23 UTC, azizsigar commented
sorry about naming 😅

2024-04-30 07:52 UTC, azizsigar commented
updated x2,x4

2024-05-04 15:06 UTC, tlorent requested changes
Nice job @azizsigar , great! 🥇 I don't have a lot to comment, only one thing to note about using `.length` on an object. If you can change that then I can approve the PR! 🙌

2024-05-04 15:06 UTC, tlorent commented on 1-JavaScript/Week2/assignment/ex1-giveCompliment.js
Great work! 😄

2024-05-04 15:06 UTC, tlorent commented on 1-JavaScript/Week2/assignment/ex2-dogYears.js
> +ok
```suggestion
```

This can be removed? 😅

2024-05-04 15:06 UTC, tlorent commented on 1-JavaScript/Week2/assignment/ex2-dogYears.js
> +const calculateDogAge=(num)=> num*7
Almost! It should also do a `console.log` with some information about the dog's years. Can you try to add that? 🙂

2024-05-04 15:06 UTC, tlorent commented on 1-JavaScript/Week2/assignment/ex3-tellFortune.js
Nice one! 🙌

2024-05-04 15:06 UTC, tlorent commented on 1-JavaScript/Week2/assignment/ex4-shoppingCart.js
> +  return `You bought ${shoppingCart.join(", ")}!`;
Awesome! 💪

2024-05-04 15:06 UTC, tlorent commented on 1-JavaScript/Week2/assignment/ex6-totalCost.js
> +}
Great use of `.reduce` and using `Object.values()` to get the values of each property! 🤩 

However, you are using the `length` property on an object and that does not exist. So if you want to check if there are no prices you need another way to find out if the object is empty 🙂

2024-05-04 15:06 UTC, tlorent commented on 1-JavaScript/Week2/assignment/ex7-mindPrivacy.js
> +
🥇

2024-05-13 07:52 UTC, tlorent reviewed
Looks good @azizsigar ! 🤩 Just one more comment about the length of an object.

2025-03-01 10:32 UTC, closed without merging