Alishka w 2
HackYourAssignment/Assignments-cohort48 pull request #15
Opened 2024-04-30 13:52 UTC by Alishka-Space

2024-05-08 10:58 UTC, DanielGordon1 requested changes
Nice work, I think you did great on most of the assignments! 💯 

I left some questions/remarks here and there, some things are more important than others.

Regarding the `ShoppingCartPure` exercise I would definitely require you to revert the changes you made to the tests, and see if you can get the assignment to pass.

All in all good work 👍🏽

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex3-tellFortune.js
> +  let randomIndex =Math.floor(Math.random()* array.length)
✅

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex3-tellFortune.js
> +  let wife = selectRandomly(partnerNames);
✅

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex3-tellFortune.js
> +  let wife = selectRandomly(partnerNames);
We could use `const` for all these variables. :)

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex3-tellFortune.js
> +  let randomIndex =Math.floor(Math.random()* array.length)
We could use `const` for this variable. :)

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex4-shoppingCart.js
> +function addToShoppingCart(/* parameters go here */item) {
Next time could you remove the comment `/* parameters go here */`, this goes for all the functions. That way its easier to read what the params are 🙏🏽

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex4-shoppingCart.js
> +  if (item!==undefined) {
It would be nice if we would also handle `null` `false` or any non true value instead of only checking for `undefined`. I would suggest doing a `truthy` check .

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex4-shoppingCart.js
> +  return `You bought ${shoppingCart.join(", ")}!`;
💯

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex4-shoppingCart.js
> +    if (shoppingCart.length>3) {
💯

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex5-shoppingCartPure.js
> +  const newCart = [...cart];
Do you think we could we do this in a different way using a one-liner, array destructuring, and the `slice` method?

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex5-shoppingCartPure.js
> +  const result = addToShoppingCart(initialCart.slice(), 'chocolate');
I dont think you are supposed to edit the tests.

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex5-shoppingCartPure.js
> +  const result = addToShoppingCart(initialCart.slice(), 'waffles');
Same comment as above.

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex6-totalCost.js
> +  console.log(result);   // Output: Total: €4.48
You can use `console.assert(expected == result)` to verify the output.

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex6-totalCost.js
> +  console.log(result);  // Output: Total: €58.50
Same comment as above :)

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex6-totalCost.js
> +    if (typeof cart[item] === 'number') {
This is functionally correct 💯 !
Alternatively do you think we could use `Object.values` and a `forEach` loop here?

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex7-mindPrivacy.js
> +function filterPrivateData(/* TODO parameter(s) go here */array) {
I would suggest naming the param something less generic than array, what kind of objects are we handling here? That way we the person reading the code can more quickly understand the context. Something like `employees` might suffice.

2024-05-08 10:58 UTC, DanielGordon1 commented on 1-JavaScript/Week2/assignment/ex7-mindPrivacy.js
> +  return array.map( ({name,occupation,email})=>({name,occupation,email})
🥇

2024-05-18 21:55 UTC, Alishka-Space commented on 1-JavaScript/Week2/assignment/ex1-giveCompliment.js
> +  let random = Math.floor(Math.random() * compliments.length);
hello @DanielGordon1 thank you for Advising and reviewing i made change on w-2-java assignment  !

2024-05-28 19:55 UTC, DanielGordon1 requested changes
Nice improvements and cleanup. 💯 

There are still some issues to resolve though; make sure you run you code before submitting it again so you know for sure that you didn't miss any typos or spelling mistakes!

Good luck 💪🏽

2024-07-08 10:49 UTC, DanielGordon1 approved these changes
Nice work on the final push 🥇

2025-01-15 10:55 UTC, closed without merging