Alishka w 3
HackYourAssignment/Assignments-cohort48 pull request #31
Opened 2024-05-07 21:06 UTC by Alishka-Space

2024-05-13 20:49 UTC, DanielGordon1 reviewed
All in all, very solid work this week ! 🥇 

I left a bunch of comments, some more important than others.
Would be great if you can have a look at those!

Especially exercise 3 and 5 need some extra work. 🙏🏽 

For exercise 5 I am also missing a bugfix in the code. Please check the Readme for instructions 🤝

2024-05-13 20:49 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex2-mondaysWorth.test.js
> +console.log(computeEarnings(mondayTasks, hourlyRate));
We can probably remove this console.log right ? 🧹

2024-05-13 20:49 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex3-lemonAllergy.test.js
> +  const wantedFruits = fruitArray.filter((fruit) => fruit !== unwantedFruit);
💯

2024-05-13 20:49 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex3-lemonAllergy.test.js
> +
I think we're missing a call to the `sanitizeFruitBasket` function here.

Tip: We want to test if the original basket remains the same after we've invoked the function that filters out items. 

🙏🏽

2024-05-13 20:49 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex3-lemonAllergy.test.js
> +    expect(sanitizeFruitBasket(fruitBasket, 'lemon')).not.toContain('lemon');
🥇

2024-05-13 20:49 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex4-observable/ex4-observable.js
> +      subscribers.forEach((x) => x(message))
What does `x` mean in this context?

2024-05-13 20:49 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex5-wallet/index.js
> +    answer:b,
✅

2024-05-13 20:49 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex5-wallet/index.js
> +    answer:c,
✅

2024-05-13 20:49 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex5-wallet/index.js
> +    answer: a,
✅

2024-05-13 20:49 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex5-wallet/index.js
> +    answer: b,
This is incorrect unfortunately! :(

2024-05-13 20:49 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex5-wallet/index.js
> +    answer:c,
✅

2024-05-13 20:50 UTC, DanielGordon1 requested changes
Please see my previous review for details!

2024-05-20 16:12 UTC, Alishka-Space commented on 1-JavaScript/Week3/assignment/ex1-doubleEvenNumbers.test.js
> +  const evenNumbers = numbers.filter((e) => e % 2 === 0)
sorry i meant the (e) the "Element" or number

2024-05-20 16:15 UTC, Alishka-Space commented on 1-JavaScript/Week3/assignment/ex4-observable/ex4-observable.js
> +      subscribers.forEach((x) => x(message))
Bardon me i meant "x" current element  subscriber and i change it !

2024-05-20 16:15 UTC, Alishka-Space commented on 1-JavaScript/Week3/assignment/ex5-wallet/index.js
> +    answer: b,
i made rechecked for it again !

2024-05-20 16:18 UTC, Alishka-Space commented
could you please REcheck my assignment and feed it back , i made change for w-2 and w-3 please !

2024-05-28 20:35 UTC, DanielGordon1 approved these changes
Nice work on making the necessary changes!

You did a great job 🥇 

Approved 🤝

2024-05-28 20:35 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex2-mondaysWorth.test.js
> +          return `€${totalEarnings}`;
Can you make sure the indentation is done properly and the code is formatted well?
That way the code is more easily readable 🙏🏽 
```suggestion
  const totalEarnings = tasks
    .map(task => (task.duration/60) * rate)
    .reduce((acc, curr) => acc + curr, 0)     
  return `€${totalEarnings}`;
```

2024-05-28 20:35 UTC, DanielGordon1 commented on 1-JavaScript/Week3/assignment/ex5-wallet/index.js
> +};
💯

2025-01-15 10:55 UTC, closed without merging