Yousra Browser week1
HackYourAssignment/Assignments-cohort48 pull request #41
Opened 2024-05-21 14:11 UTC by YousraElmag

2024-06-08 08:57 UTC, imtiaz101325 requested changes
Great work so far. Just have a few comments you need to look into.

Please look into the code formatting, moving styles to CSS files and the dancing cat logic. 🙏🏾

2024-06-08 08:57 UTC, imtiaz101325 commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
The logic is a bit wrong. Your dancing cat should not keep moving. Please give it another shot. 🙏🏾

2024-06-08 08:57 UTC, imtiaz101325 commented on 2-Browsers/Week1/assignment/ex3-hijackLogo.js
> +  var logo = document.querySelector('img[alt="Google"]');
Great use of selector!

2024-06-08 08:57 UTC, imtiaz101325 commented on 2-Browsers/Week1/assignment/ex3-hijackLogo.js
💯

2024-06-08 11:04 UTC, YousraElmag commented
Thank you very much for your comments. I have made the required changes

2024-06-22 08:39 UTC, imtiaz101325 approved these changes
Looking good!

I don't know why but the bookList exercise is a bit wrong now. Please look into if you want but I am still approving this.

2024-06-22 08:39 UTC, imtiaz101325 commented on 2-Browsers/Week1/assignment/ex1-bookList/index.js
> +      isbn: 'https://hackyourfuture.github.io/example-pages/Browsers/Week1/1-booklist/assets/the_pragmatic_programmer.jpg',
I don't think you are supposed to change the data like this.

2024-06-22 08:39 UTC, imtiaz101325 commented on 2-Browsers/Week1/assignment/ex1-bookList/index.js
> +<img src="${book.isbn}"alt=""></li>`
You should generate the `src` using title instead of modifying the data.

2024-06-22 08:39 UTC, imtiaz101325 commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
Good job!

2024-11-29 09:18 UTC, closed without merging