Browsers module week1 Ali
HackYourAssignment/Assignments-cohort48 pull request #47
Opened 2024-05-25 07:24 UTC by Alishka-Space

Adding assignments for Browsers module Week 1 Ali

2024-05-25 11:13 UTC, keremilhan requested changes

2024-05-25 11:13 UTC, keremilhan commented on 2-Browsers/Week1/assignment/ex4-whatsTheTime/index.js
> +    const formattedTime = `${hours}:${minutes}:${seconds}`;
- You can simply use `new Date().toLocaleTimeString();` to show the current time.

2024-05-25 11:13 UTC, keremilhan commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +           catLeftPosition = 0;
- If you change this line to 
`catLeftPosition = -cat.offsetWidth`
cat walking will look more continuous.

2024-05-25 11:13 UTC, keremilhan commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +   const catMiddlePosition = (screenWidth - cat.width) / 2;
- Using `offsetWidth` instead of `width` is better in this scenario.

2024-05-25 11:13 UTC, keremilhan commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
>  -----------------------------------------------------------------------------*/
- create a function called catWalk and then add this function into event listener like the following
`window.addEventListener('load', catWalk);`

2024-05-25 11:13 UTC, keremilhan commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +   const cat = document.getElementById('img');
- Consider storing the values for STEP_SIZE_PX, STEP_TIME_MS, and DANCE_TIME_MS in variables. This approach will make your function more flexible, easier to change, and reusable.
For instance:

```
const STEP_SIZE_PX = 10; // Step size in pixels

const STEP_TIME_MS = 50; // Step time in milliseconds

const DANCE_TIME_MS = 5000; // Dance time in milliseconds
```

2024-05-30 10:52 UTC, Alishka-Space commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +   const cat = document.getElementById('img');
ya true thank you i add variables !

2024-05-30 11:15 UTC, Alishka-Space commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +   const catMiddlePosition = (screenWidth - cat.width) / 2;
done !i add offsetwidth.

2024-05-30 11:16 UTC, Alishka-Space commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +           catLeftPosition = 0;
done !

2024-05-30 11:27 UTC, Alishka-Space commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
>  -----------------------------------------------------------------------------*/
add it

2024-05-30 11:36 UTC, keremilhan commented on 2-Browsers/Week1/assignment/ex4-whatsTheTime/index.js
> +    const formattedTime = `${hours}:${minutes}:${seconds}`;
- Please always test your code by opening the index.js file with live server before pushing your code. The time can not be seen in the browser because 
`const timeElement = document.getElementById('formattedTime')`
there is no element with id of "formattedTime". You should first create it.

2024-05-30 11:39 UTC, keremilhan requested changes
- **ex4-whatsTheTime**
Please always test your code by opening the index.html file with live server before pushing your code. The time can not be seen in the browser because
`const timeElement = document.getElementById('formattedTime')`
there is no element with id of "formattedTime". You should first create it.

2024-05-30 12:07 UTC, keremilhan approved these changes

2025-01-15 10:55 UTC, closed without merging