added12345
HackYourAssignment/Assignments-cohort48 pull request #48
Opened 2024-05-25 09:19 UTC by azizsigar

only assigmt not prep ex 6

2024-05-25 10:50 UTC, keremilhan requested changes

2024-05-25 10:50 UTC, keremilhan commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +  let imgWidth = img.width;
- Using `offsetWidth` instead of `width` is a better practice in our scenario.

2024-05-25 10:50 UTC, keremilhan commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +
- Ensure the cat's walk is continuous. When it reaches the end of the screen, it should immediately reappear from the beginning, starting with its head first and then continuing the walk smoothly.
- When the cat is dancing in the middle, the walking cat image appears for a second and then it continues dancing for 5 more seconds. It should dance for only 5 seconds and then continue walking.

2024-05-25 10:50 UTC, keremilhan commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +
- Consider storing the values for STEP_SIZE_PX, STEP_TIME_MS, and DANCE_TIME_MS in variables. This approach will make your function more flexible, easier to change, and reusable.
For instance:

```
const STEP_SIZE_PX = 10; // Step size in pixels

const STEP_TIME_MS = 50; // Step time in milliseconds

const DANCE_TIME_MS = 5000; // Dance time in milliseconds
```

2024-05-27 15:44 UTC, keremilhan requested changes
- Please solve this bug: When the cat is dancing in the middle, after 5 seconds the walking cat image appears for a second and then it continues dancing for 5 more seconds. It should dance for only 5 seconds and then continue walking.

2024-05-28 16:26 UTC, keremilhan requested changes

2024-05-28 16:26 UTC, keremilhan commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +   const STEP_TIME_MS = 50;
- You are not using this variable. You can remove this line.

2024-05-28 16:31 UTC, azizsigar commented on 2-Browsers/Week1/assignment/ex5-catWalk/index.js
> +   const STEP_TIME_MS = 50;
Done

2024-05-28 16:36 UTC, keremilhan requested changes

2024-05-28 16:42 UTC, keremilhan approved these changes

2025-03-01 10:31 UTC, closed without merging